[package]
name = "flow"
entrypoint = "src/lib.typ"
exclude = ["doc/*", "thumbnail/generate", "install.sh"]

license = "MIT"
authors = ["MultisampledNight <@MultisampledNight>"]
repository = "https://github.com/MultisampledNight/flow"

description = "A few templates and too many scattered utils."
categories = ["components", "report"]
keywords = ["pkm", "notes", "checklist"]

version = "0.1.1"
compiler = "0.12.0"


[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail/page-1.png"
