[package]
name = "flow"
version = "0.1.0"
entrypoint = "src/lib.typ"

license = "MIT"
description = "Random note template and utilities for Multi's PKM system."
categories = ["components", "report", "book"]
authors = ["MultisampledNight"]
repository = "https://github.com/MultisampledNight/flow"
