[package]
name = "flow"
version = "0.1.0"
entrypoint = "src/lib.typ"

license = "MIT"
description = "Random note template and utilities for Multi's PKM system."
categories = ["components", "report"]
authors = ["MultisampledNight"]
repository = "https://github.com/MultisampledNight/flow"

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail/page-1.png"
