#!/usr/bin/env zsh
set -xeuo pipefail
source `dirname $0`/common

mkdir -p "$target"
query="`dirname $0`/flow-query"

for source in "$@"; do
	args=(
		--input theme=duality
		--input "filename=`basename "$source"`"
		--root "$notes"
	)

	mkdir -p ./target
	title=`$query "$source" 2>/dev/null | jq -r .title`
	typst compile \
		"$source" "$target/$title.pdf" \
		$args 2>/dev/null
done
