#!/usr/bin/env zsh
# Queries the given note files, or *all* notes if none given.
# Prints JSON.
set -euo pipefail
here=`dirname $0`
source "$here/common"

cmd=("$here/flow" info)

if [[ ${#@} > 0 ]]; then
	for note in "$@"; do
		$cmd "$note" '<info>'
	done
else
	fd -0 --exclude zero/template '\.typ$' "$notes" \
		| xargs -P `nproc` -0 -n 1 $cmd
fi
